# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def replace_null_fields(app, schema_editor):
    UserProfile = app.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.transportation = profile.transportation or ''
        profile.transportation_fee = profile.transportation_fee or ''
        profile.roommate = profile.roommate or ''
        profile.personal_id = profile.personal_id or ''
        profile.ice_contact = profile.ice_contact or ''
        profile.ice_phone = profile.ice_phone or ''
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0007_auto_20170508_0251'),
    ]

    operations = [
        migrations.RunPython(replace_null_fields),
        migrations.AddField(
            model_name='userprofile',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='require_printed_cert',
            field=models.BooleanField(default=False, help_text='require printed certificate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='birthday, for insurance', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cel_dinner',
            field=models.BooleanField(default=False, help_text='need for celebratory dinner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.BooleanField(default=True, help_text='need for certificate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ice_contact',
            field=models.CharField(blank=True, default='', help_text='Emergency contact info', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ice_phone',
            field=models.CharField(blank=True, default='', help_text='emergency contact number', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.OneToOneField(blank=True, default=None, help_text='language abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_id',
            field=models.CharField(blank=True, default='', help_text='id number, for insurance', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_worker',
            field=models.BooleanField(default=False, help_text='if is previously a conference staff'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roommate',
            field=models.CharField(blank=True, default='', help_text='requested roommate', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='transportation method', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_aid',
            field=models.BooleanField(default=False, help_text='if need transportation fee aid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_fee',
            field=models.CharField(blank=True, default='', help_text='transportation fee', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_hr',
            field=models.BooleanField(default=False, help_text='if transportation time >= 1hr'),
        ),
    ]
