# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_fields_replace_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='legal',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\xb3\x95\xe5\xbe\x8b'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='medical',
            field=models.BooleanField(default=False, verbose_name=b'\xe9\x86\xab\xe7\x99\x82'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='pr',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x85\xac\xe9\x97\x9c'),
        ),
        migrations.AlterField(
            model_name='language',
            name='cantonese',
            field=models.BooleanField(default=False, verbose_name=b'\xe7\xb2\xb5\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='english',
            field=models.BooleanField(default=False, verbose_name=b'\xe8\x8b\xb1\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='japanese',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x97\xa5\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='taiwanese',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x8f\xb0\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female'), (9, b'Other')], help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.OneToOneField(blank=True, default=None, help_text=b'language abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Language'),
        ),
    ]
