# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0003_auto_20151227_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_id',
        ),
        migrations.AddField(
            model_name='registertoken',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead_team',
            field=models.ForeignKey(blank=True, default=None, help_text='leading team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='other',
            field=models.CharField(blank=True, default='', help_text='other special abilities', max_length=64),
        ),
        migrations.AlterField(
            model_name='language',
            name='other',
            field=models.CharField(blank=True, default='', help_text='other language abilities', max_length=64),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='abilities',
            field=models.OneToOneField(blank=True, default=None, help_text='other abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.abilities'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accom',
            field=models.IntegerField(choices=[(0, 'Not needed'), (1, 'Either'), (2, 'Needed')], default=0, help_text='need for accommodation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='biography', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cel_dinner',
            field=models.NullBooleanField(help_text='need for celebratory dinner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.NullBooleanField(help_text='need for certificate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (9, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='department and grade / position', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.OneToOneField(blank=True, default=None, help_text='language abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_worker',
            field=models.NullBooleanField(default=False, help_text='if is previously a COSCUP worker'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(blank=True, default='', help_text='residence', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roommate',
            field=models.CharField(blank=True, default='', help_text='requested roommate', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default='', help_text='school or company', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(blank=True, default='', help_text='T-shirt size', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='transportation method', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_aid',
            field=models.NullBooleanField(default=False, help_text='if need transportation fee aid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_fee',
            field=models.CharField(blank=True, default='', help_text='transportation fee', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_hr',
            field=models.NullBooleanField(default=False, help_text='if transportation time >= 1hr'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twenty',
            field=models.NullBooleanField(default=True, help_text='if age >= 20'),
        ),
    ]
