# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20151227_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', help_text='organization/community/school/company', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='redmine',
            field=models.CharField(blank=True, default='', help_text='redmine id', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slack',
            field=models.CharField(blank=True, default='', help_text='slack nick', max_length=32),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='other',
            field=models.CharField(blank=True, default='', help_text='other special abilities', max_length=64),
        ),
        migrations.AlterField(
            model_name='language',
            name='other',
            field=models.CharField(blank=True, default='', help_text='other language abilities', max_length=64),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='abilities',
            field=models.OneToOneField(blank=True, default=None, help_text='other abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.abilities'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accom',
            field=models.IntegerField(choices=[(0, 'Not needed'), (1, 'Either'), (2, 'Needed')], default=0, help_text='need for accommodation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='biography', max_length=320),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cel_dinner',
            field=models.NullBooleanField(help_text='need for celebratory dinner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.NullBooleanField(help_text='need for certificate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (9, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.OneToOneField(blank=True, default=None, help_text='language abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_worker',
            field=models.BooleanField(default=False, help_text='if is previously a SITCON worker'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(blank=True, default='', help_text='residence', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roommate',
            field=models.ForeignKey(blank=True, default=None, help_text='requested roommate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(blank=True, default='', help_text='T-shirt size', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='transportation method', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_aid',
            field=models.BooleanField(default=False, help_text='if need transportation fee aid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_fee',
            field=models.CharField(blank=True, default='', help_text='transportation fee', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_hr',
            field=models.BooleanField(default=False, help_text='if transportation time >= 1hr'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twenty',
            field=models.BooleanField(default=True, help_text='if age >= 20'),
        ),
    ]
