# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0004_auto_20160321_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertoken',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, default='', help_text='birthday, for volunteering proof application', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead_team',
            field=models.ForeignKey(blank=True, default=None, help_text='leading team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteering_duration',
            field=models.CharField(blank=True, default='', help_text='volunteering duration, for volunteering proof application', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteering_proof',
            field=models.BooleanField(default=False, help_text='need for volunteering proof application'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteering_time',
            field=models.CharField(blank=True, default='', help_text='volunteering timespan, for volunteering proof application', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteering_work_done',
            field=models.CharField(blank=True, default='', help_text='work done for the conf., for volunteering proof application', max_length=256),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='biography', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', help_text='organization/community/school/company', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_worker',
            field=models.BooleanField(default=False, help_text='if is previously a COSCUP worker'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(blank=True, default='', help_text='residence', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roommate',
            field=models.CharField(blank=True, default='', help_text='requested roommate', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='transportation method', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_fee',
            field=models.CharField(blank=True, default='', help_text='transportation fee', max_length=128),
        ),
    ]
