# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160417_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, default='', help_text='birthday, for insurance', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ice_contact',
            field=models.CharField(blank=True, default='', help_text='Emergency contact info', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ice_phone',
            field=models.CharField(blank=True, default='', help_text='emergency contact number', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='on_site',
            field=models.NullBooleanField(default=True, help_text='if is onsite volunteer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_id',
            field=models.CharField(blank=True, default='', help_text='id number, for insurance', max_length=16, null=True),
        ),
    ]
