# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160428_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accom',
            field=models.IntegerField(choices=[(0, 'Not needed'), (1, 'Either'), (2, 'Needed')], default=2, help_text='need for accommodation'),
        ),
    ]
