# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160331_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertoken',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
