# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_registertoken_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, default='', help_text='birthday, for volunteering proof application', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', help_text='organization/community/school/company', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_id',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_worker',
            field=models.NullBooleanField(default=False, help_text='if is previously a COSCUP worker'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='redmine',
            field=models.CharField(blank=True, default='', help_text='redmine id', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(blank=True, default='', help_text='residence', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roommate',
            field=models.CharField(blank=True, default='', help_text='requested roommate', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(blank=True, default='', help_text='T-shirt size', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slack',
            field=models.CharField(blank=True, default='', help_text='slack nick', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='transportation method', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_aid',
            field=models.NullBooleanField(default=False, help_text='if need transportation fee aid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_fee',
            field=models.CharField(blank=True, default='', help_text='transportation fee', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation_hr',
            field=models.NullBooleanField(default=False, help_text='if transportation time >= 1hr'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twenty',
            field=models.NullBooleanField(default=True, help_text='if age >= 20'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='volunteering_duration',
            field=models.CharField(blank=True, default='', help_text='volunteering duration, for volunteering proof application', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='volunteering_proof',
            field=models.NullBooleanField(default=False, help_text='need for volunteering proof application'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='volunteering_time',
            field=models.CharField(blank=True, default='', help_text='volunteering timespan, for volunteering proof application', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='volunteering_work_done',
            field=models.CharField(blank=True, default='', help_text='work done for the conf., for volunteering proof application', max_length=256, null=True),
        ),
    ]
