# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160501_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.BooleanField(default=False, verbose_name=b'\xe9\x86\xab\xe7\x99\x82')),
                ('legal', models.BooleanField(default=False, verbose_name=b'\xe6\xb3\x95\xe5\xbe\x8b')),
                ('pr', models.BooleanField(default=False, verbose_name=b'\xe5\x85\xac\xe9\x97\x9c')),
                ('other', models.CharField(blank=True, default=b'', help_text=b'other special abilities', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='abilities',
        ),
        migrations.AlterField(
            model_name='language',
            name='cantonese',
            field=models.BooleanField(default=False, verbose_name=b'\xe7\xb2\xb5\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='english',
            field=models.BooleanField(default=False, verbose_name=b'\xe8\x8b\xb1\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='japanese',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x97\xa5\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='language',
            name='taiwanese',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x8f\xb0\xe8\xaa\x9e'),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='display_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='email',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='username',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='abilities',
            field=models.OneToOneField(blank=True, default=None, help_text=b'other abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Ability'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=b'', help_text=b'biography', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, default=b'', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default=b'', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female'), (9, b'Other')], help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, default=b'', help_text=b'department and grade / position', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.OneToOneField(blank=True, default=None, help_text=b'language abilities', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=b'', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default=b'', help_text=b'school or company', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=32),
        ),
    ]
