# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0007_auto_20160412_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lead_team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead_team',
            field=models.ManyToManyField(blank=True, default=None, help_text='leading team', null=True, related_name='leader', to='auth.Group'),
        ),
    ]
