# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170627_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilities',
            name='medical',
            field=models.BooleanField(default=False, verbose_name='醫療或急救'),
        ),
    ]
