# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_open', models.BooleanField(default=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('assign_issue', 'Assign issues to others'), ('label_issue', 'Label issues'), ('toggle_issue', 'Close or reopen issues'), ('comment_issue', 'Comment on issues')),
            },
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mode', models.CharField(choices=[('.', 'Commented'), ('C', 'Closed'), ('R', 'Reopened'), ('M', 'Merged to'), ('I', 'Merged in'), ('A', 'Assigned to'), ('a', 'Unassigned'), ('+', 'Labeled'), ('-', 'Unlabeled'), ('D', 'Set due time to')], default='.', editable=False, max_length=1)),
                ('content', models.TextField()),
                ('issue', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='issues.Issue')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='issue_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='issues', to='issues.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='starring',
            field=models.ManyToManyField(blank=True, null=True, related_name='starred_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
