# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('@', 'E-Mail'), ('+', 'SMS')], default='@', max_length=1)),
                ('sender', models.CharField(blank=True, default='', max_length=160)),
                ('receiver', models.CharField(max_length=160)),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
